### ISSUE TITLE
New format

### ISSUE THREAD

**Issue by jakast002** [xdrazkov/flight-scraper#4]
Update format of links as shown below:

![IMG_4915](https://github.com/user-attachments/assets/1ce896d0-3082-46fc-a6a0-f370fc054d64)

**Comment by jakast002** [comment]
Normal:

[• 19. - 20. september 2024 za 55€](https://wizzair.com/)
   (pondelok 7:15-8:40 - utorok 18:20-20:45)

Airline mix:

• 19. - 20. september 2024 za 55€:
   [odkaz tam](https://wizzair.com/) + [odkaz naspäť](https://www.ryanair.com/)
   (pondelok 7:15-8:40 - utorok 18:20-20:45)

Route mix:

• 19. - 20. september 2024 za 55€:
   [odkaz tam VIE-CFU](https://www.ryanair.com/) + [odkaz naspäť CFU-BTS](https://www.ryanair.com/)
   (pondelok 7:15-8:40 - utorok 18:20-20:45)

Airline+route mix:

• 19. - 20. september 2024 za 55€:
   [odkaz tam VIE-CFU](https://wizzair.com/) + [odkaz naspäť CFU-BTS](https://www.ryanair.com/)
   (pondelok 7:15-8:40 - utorok 18:20-20:45)

**Comment by iwezfuf** [comment]
resolved in 625695d

**Comment by jakast002** [comment]
1. Replace (-) with bullet points (•) at the start of each link.
2. Add <br /> after each day+time.
3. Change the formatting of the end (after last day+time) as shown below: </p> on the same line as last day+time, no empty line, then <br /> twice as shown.


CORRECT - ADJUSTED:
<p><a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-08/1/0/0/null">• 6. - 8. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - utorok 6:30-8:15)<br />
<a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-09/1/0/0/null">• 6. - 9. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - streda 6:40-8:25)<br />
<a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-10/1/0/0/null">• 6. - 10. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - štvrtok 6:40-8:25)<br />


WRONG - CURRENT VERSION:
<p><a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-08/1/0/0/null">- 6. - 8. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - utorok 6:30-8:15) <a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-09/1/0/0/null">- 6. - 9. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - streda 6:40-8:25) <a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-10/1/0/0/null">- 6. - 10. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - štvrtok 6:40-8:25) <a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-13/2024-10-15/1/0/0/null">- 13. - 15. október 2024 za 20€</a><br />


WRONG END - CURRENT VERSION:
<a href=https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-23/2024-10-25/1/0/0/null>- 23. - 25. október 2024 za 20€</a><br />
(streda 6:00-7:40 - piatok 6:40-8:25)
</p>

Uvedené ceny sú platné k 11. 9. 2024 o 10:00.


CORRECT END - ADJUSTED:
<a href="https://wizzair.com/sk-sk/booking/select-flight/VIE/FCO/2024-10-06/2024-10-10/1/0/0/null">• 6. - 10. október 2024 za 20€</a><br />
(nedeľa 6:00-7:40 - štvrtok 6:40-8:25)</p>
Uvedené ceny sú platné k 11. 9. 2024 o 09:58.<br />
<br />

**Comment by jakast002** [comment]
Fixed
